#ifndef __GENERATED_CSR_H
#define __GENERATED_CSR_H

/* CNTRL */
#define CSR_CNTRL_BASE 0xd000
#define CSR_CNTRL_CNTRL_ADDR 0xd000
#define CSR_CNTRL_CNTRL_SIZE 16
#define CSR_CNTRL_ENABLE_ADDR 0xd040
#define CSR_CNTRL_ENABLE_SIZE 1
#define CSR_CNTRL_TEST_ADDR 0xd044
#define CSR_CNTRL_TEST_SIZE 1
#define CSR_CNTRL_NDMA_ADDR 0xd048
#define CSR_CNTRL_NDMA_SIZE 1

/* pcie_dma0 */
#define CSR_PCIE_DMA_BASE(DMA_NR) (0xa800+0x800*DMA_NR)
#define CSR_PCIE_DMA_WRITER_ENABLE_ADDR(DMA_NR) (0xa800+0x800*DMA_NR)
#define CSR_PCIE_DMA_WRITER_ENABLE_SIZE 1
#define CSR_PCIE_DMA_WRITER_ALLOW_REQUESTS_ADDR(DMA_NR) (0xa804+0x800*DMA_NR)
#define CSR_PCIE_DMA_WRITER_ALLOW_REQUESTS_SIZE 1
#define CSR_PCIE_DMA_WRITER_TABLE_VALUE_ADDR(DMA_NR) (0xa808+0x800*DMA_NR)
#define CSR_PCIE_DMA_WRITER_TABLE_VALUE_SIZE 2
#define CSR_PCIE_DMA_WRITER_TABLE_WE_ADDR(DMA_NR) (0xa810+0x800*DMA_NR) 
#define CSR_PCIE_DMA_WRITER_TABLE_WE_SIZE 1
#define CSR_PCIE_DMA_WRITER_TABLE_LOOP_PROG_N_ADDR(DMA_NR) (0xa814+0x800*DMA_NR)  
#define CSR_PCIE_DMA_WRITER_TABLE_LOOP_PROG_N_SIZE 1
#define CSR_PCIE_DMA_WRITER_TABLE_LOOP_STATUS_ADDR(DMA_NR) (0xa818+0x800*DMA_NR)  
#define CSR_PCIE_DMA_WRITER_TABLE_LOOP_STATUS_SIZE 1
#define CSR_PCIE_DMA_WRITER_TABLE_LEVEL_ADDR(DMA_NR) (0xa81c+0x800*DMA_NR)  
#define CSR_PCIE_DMA_WRITER_TABLE_LEVEL_SIZE 1
#define CSR_PCIE_DMA_WRITER_TABLE_FLUSH_ADDR(DMA_NR) (0xa820+0x800*DMA_NR)  
#define CSR_PCIE_DMA_WRITER_TABLE_FLUSH_SIZE 1
#define CSR_PCIE_DMA_READER_ENABLE_ADDR(DMA_NR) (0xa824+0x800*DMA_NR)  
#define CSR_PCIE_DMA_READER_ENABLE_SIZE 1
#define CSR_PCIE_DMA_READER_PACKET_NR_ADDR(DMA_NR) (0xa828+0x800*DMA_NR)  
#define CSR_PCIE_DMA_READER_PACKET_NR_SIZE 1
#define CSR_PCIE_DMA_READER_TABLE_VALUE_ADDR(DMA_NR) (0xa82c+0x800*DMA_NR)  
#define CSR_PCIE_DMA_READER_TABLE_VALUE_SIZE 2
#define CSR_PCIE_DMA_READER_TABLE_WE_ADDR(DMA_NR) (0xa834+0x800*DMA_NR)  
#define CSR_PCIE_DMA_READER_TABLE_WE_SIZE 1
#define CSR_PCIE_DMA_READER_TABLE_LOOP_PROG_N_ADDR(DMA_NR) (0xa838+0x800*DMA_NR)  
#define CSR_PCIE_DMA_READER_TABLE_LOOP_PROG_N_SIZE 1
#define CSR_PCIE_DMA_READER_TABLE_LOOP_STATUS_ADDR(DMA_NR) (0xa83c+0x800*DMA_NR)  
#define CSR_PCIE_DMA_READER_TABLE_LOOP_STATUS_SIZE 1
#define CSR_PCIE_DMA_READER_TABLE_LEVEL_ADDR(DMA_NR) (0xa840+0x800*DMA_NR)  
#define CSR_PCIE_DMA_READER_TABLE_LEVEL_SIZE 1
#define CSR_PCIE_DMA_READER_TABLE_FLUSH_ADDR(DMA_NR) (0xa844+0x800*DMA_NR)  
#define CSR_PCIE_DMA_READER_TABLE_FLUSH_SIZE 1
#define CSR_PCIE_DMA_READER_CURRENT_PACKET_ADDR(DMA_NR) (0xa848+0x800*DMA_NR)
#define CSR_PCIE_DMA_READER_CURRENT_PACKET_SIZE 1
#define CSR_PCIE_DMA_READER_FLUSH_NR_ADDR(DMA_NR) (0xa84c+0x800*DMA_NR)  
#define CSR_PCIE_DMA_READER_FLUSH_NR_SIZE 1
#define CSR_PCIE_DMA_READER_FLUSH_NBYTES_ADDR(DMA_NR) (0xa850+0x800*DMA_NR)  
#define CSR_PCIE_DMA_READER_FLUSH_NBYTES_SIZE 1

/* identifier_mem */
#define CSR_IDENTIFIER_MEM_BASE 0x800

/* constants */
#define CSR_DATA_WIDTH 32
#define SYSTEM_CLOCK_FREQUENCY 125000000
#define CONFIG_CLOCK_FREQUENCY 125000000
#define CONFIG_CSR_DATA_WIDTH 32

#endif
